        // デモ用のシークレット一覧
        const PLACEHOLDER_API_KEY = "api_key_1234567890abcdef1234567890abcdef";
        const PLACEHOLDER_AWS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY";
        const PLACEHOLDER_GITHUB_TOKEN = "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";
